# Generated by Django 3.1.4 on 2020-12-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('plant', models.CharField(max_length=20)),
            ],
        ),
    ]
